"""add_excedente_tipo_y_motivo

Revision ID: 80ac08be5355
Revises: b8c2d4e6f901
Create Date: 2026-06-23 16:59:46.431318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ac08be5355'
down_revision = 'b8c2d4e6f901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('acopio_paquetes_numero_key', 'acopio_paquetes', type_='unique')
    op.drop_index('ix_acopio_paquetes_numero', table_name='acopio_paquetes')
    op.create_index(op.f('ix_acopio_paquetes_numero'), 'acopio_paquetes', ['numero'], unique=True)
    op.add_column('imputaciones', sa.Column('excedente_tipo', sa.String(length=50), nullable=True))
    op.add_column('imputaciones', sa.Column('excedente_motivo', sa.String(length=1200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imputaciones', 'excedente_motivo')
    op.drop_column('imputaciones', 'excedente_tipo')
    op.drop_index(op.f('ix_acopio_paquetes_numero'), table_name='acopio_paquetes')
    op.create_index('ix_acopio_paquetes_numero', 'acopio_paquetes', ['numero'], unique=False)
    op.create_unique_constraint('acopio_paquetes_numero_key', 'acopio_paquetes', ['numero'])
    # ### end Alembic commands ###
