"""change_excedente_motivo_to_text

Revision ID: b9b2f03f1d9f
Revises: 80ac08be5355
Create Date: 2026-07-06 13:26:21.694607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b2f03f1d9f'
down_revision = '80ac08be5355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imputaciones', 'excedente_motivo',
               existing_type=sa.VARCHAR(length=1200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imputaciones', 'excedente_motivo',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1200),
               existing_nullable=True)
    # ### end Alembic commands ###
