"""make_pedido_obra_id_nullable

Revision ID: 58e60f26c21a
Revises: 2bbca2135805
Create Date: 2026-03-19 19:58:20.771082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e60f26c21a'
down_revision = '2bbca2135805'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'obra_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'obra_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
