"""add_unidades_tracking

Revision ID: 2bbca2135805
Revises: 2b8d9f92e34a
Create Date: 2026-03-19 15:08:09.924330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbca2135805'
down_revision = '2b8d9f92e34a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('acopio_items', sa.Column('saldo_cantidad', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('acopios', sa.Column('total_unidades', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('acopios', sa.Column('saldo_unidades', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('imputaciones', sa.Column('cantidad_unidades', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imputaciones', 'cantidad_unidades')
    op.drop_column('acopios', 'saldo_unidades')
    op.drop_column('acopios', 'total_unidades')
    op.drop_column('acopio_items', 'saldo_cantidad')
    # ### end Alembic commands ###
