"""Initial migration

Revision ID: bd85c5eb1f16
Revises: 
Create Date: 2026-02-06 16:10:16.945335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd85c5eb1f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('comprobantes',
    sa.Column('tipo', sa.Enum('FAC_ANTICIPO', 'RECIBO', 'FAC_MERCADERIA', 'NC', name='tipocomprobante'), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobantes_id'), 'comprobantes', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ruta_storage', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('extracciones_ia',
    sa.Column('contenido_extraido', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracciones_ia_id'), 'extracciones_ia', ['id'], unique=False)
    op.create_table('obras',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'PAUSADA', 'FINALIZADA', 'CANCELADA', name='estadoobra'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_id'), 'obras', ['id'], unique=False)
    op.create_table('acopios',
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACTIVO', 'PARCIALMENTE_CONSUMIDO', 'CONSUMIDO', 'VENCIDO', 'CANCELADO', name='estadoacopio'), nullable=False),
    sa.Column('total_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_vencimiento_precio', sa.Date(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acopios_id'), 'acopios', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'EN_PREPARACION', 'ENTREGADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('total_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('acopio_items',
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('tipologia', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('total_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acopio_items_id'), 'acopio_items', ['id'], unique=False)
    op.create_table('afectaciones_acopio',
    sa.Column('importe', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopios.id'], ),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afectaciones_acopio_id'), 'afectaciones_acopio', ['id'], unique=False)
    op.create_table('presupuestos',
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presupuestos_id'), 'presupuestos', ['id'], unique=False)
    op.create_table('remitos',
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remitos_id'), 'remitos', ['id'], unique=False)
    op.create_table('acopio_item_panos',
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('ancho', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('alto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('superficie_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('perimetro_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['acopio_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acopio_item_panos_id'), 'acopio_item_panos', ['id'], unique=False)
    op.create_table('imputaciones',
    sa.Column('cantidad_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_ml', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_pesos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('es_excedente', sa.Boolean(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('acopio_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopios.id'], ),
    sa.ForeignKeyConstraint(['acopio_item_id'], ['acopio_items.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imputaciones_id'), 'imputaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imputaciones_id'), table_name='imputaciones')
    op.drop_table('imputaciones')
    op.drop_index(op.f('ix_acopio_item_panos_id'), table_name='acopio_item_panos')
    op.drop_table('acopio_item_panos')
    op.drop_index(op.f('ix_remitos_id'), table_name='remitos')
    op.drop_table('remitos')
    op.drop_index(op.f('ix_presupuestos_id'), table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index(op.f('ix_afectaciones_acopio_id'), table_name='afectaciones_acopio')
    op.drop_table('afectaciones_acopio')
    op.drop_index(op.f('ix_acopio_items_id'), table_name='acopio_items')
    op.drop_table('acopio_items')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_acopios_id'), table_name='acopios')
    op.drop_table('acopios')
    op.drop_index(op.f('ix_obras_id'), table_name='obras')
    op.drop_table('obras')
    op.drop_index(op.f('ix_extracciones_ia_id'), table_name='extracciones_ia')
    op.drop_table('extracciones_ia')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_comprobantes_id'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
