"""add_acopio_item_adicionales

Revision ID: 019b4c072ae5
Revises: a1b2c3d4e5f6
Create Date: 2026-04-24 16:09:30.293680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019b4c072ae5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acopio_item_adicionales',
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('origen', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['acopio_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acopio_item_adicionales_id'), 'acopio_item_adicionales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acopio_item_adicionales_id'), table_name='acopio_item_adicionales')
    op.drop_table('acopio_item_adicionales')
    # ### end Alembic commands ###
