"""Add precios_referencia table

Revision ID: 4b842cc9d075
Revises: 019b4c072ae5
Create Date: 2026-05-07 10:33:12.645796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b842cc9d075'
down_revision = '019b4c072ae5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precios_referencia',
    sa.Column('vidrio_exterior', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vidrio_interior', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('camara_estructural', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pulido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fason_templado_exterior', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pegado_bastidor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('camara_normal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('opacificado_perimetral', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('opacificado_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('camara_offset', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('acopio_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acopio_id'], ['acopios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acopio_id')
    )
    op.create_index(op.f('ix_precios_referencia_id'), 'precios_referencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precios_referencia_id'), table_name='precios_referencia')
    op.drop_table('precios_referencia')
    # ### end Alembic commands ###
